### ISSUE TITLE
Cell tagging toolbar

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/contentmanagement#18]
It's come up a few times that having the equivalent of tags for cells would be handy metadata for a number of other use cases:
- Varying the level of detail after export (e.g., @jsvine mentioned this for readers)
- Execution of distinct code paths within a notebook (/cc @mackintg)
- Folding/unfolding sections within the notebook authoring environment

We could prototype the tagging idea here in the extension by providing a simple cell toolbar that let's the user enter a delimited list of tags for each cell. That's all this extension would do. Other extensions could then take advantage if the additional metadata in the ways listed above. If the idea grows legs, it's an enhancement proposal candidate for the notebook tool and/or document format maybe.

It could be this feature is already in the works elsewhere and I'm unaware. Opening this as a conversation starter.

/cc @ellisonbg

**Comment by ellisonbg** [comment]
@jdfreder has a prorotype of this - Jon, where is that located?

On Mon, Dec 7, 2015 at 5:47 AM, Peter Parente notifications@github.com
wrote:

> It's come up a few times that having the equivalent of tags for cells
> would be handy metadata for a number of other use cases:
> - Varying the level of detail after export (e.g., @jsvine
>   https://github.com/jsvine mentioned this for readers)
> - Execution of distinct code paths within a notebook (/cc @mackintg
>   https://github.com/mackintg)
> - Folding/unfolding sections within the notebook authoring environment
> 
> We could prototype the tagging idea here in the extension by providing a
> simple cell toolbar that let's the user enter a delimited list of tags for
> each cell. That's all this extension would do. Other extensions could then
> take advantage if the additional metadata in the ways listed above. If the
> idea grows legs, it's an enhancement proposal candidate for the notebook
> tool and/or document format maybe.
> 
> It could be this feature is already in the works elsewhere and I'm
> unaware. Opening this as a conversation starter.
> 
> /cc @ellisonbg https://github.com/ellisonbg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter-incubator/contentmanagement/issues/18.

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by parente** [comment]
Is it https://github.com/jdfreder/ipython-celltagging?

**Comment by jdfreder** [comment]
Yeah that was where it was going to land.  It lives in a PR against ipython/ipython, and never got moved into that repo.  https://github.com/ipython/ipython/pull/6638

**Comment by stevengj** [comment]
Any chance of reviving this?

**Comment by parente** [comment]
Implemented in notebook 5.0.
