### ISSUE TITLE
Jupyter Hub runtime

### ISSUE THREAD

**Issue by abjer** [jupyter-incubator/contentmanagement#27]
I am working on a Jupyter Hub notebook server. When attempting `%load_ext jupyter_cms` I have the following OSError: 

> [Errno 2] No such file or directory: '/home/[user_id]/.local/share/jupyter/runtime'

All of the dependencies are installed but the load still fails.

**Comment by parente** [comment]
@abjer thanks for the report. Can you confirm what version of the notebook server is running on Jupyter Hub? Help menu in a notebook will show it.

**Comment by abjer** [comment]
Thanks for the reply, notebook server is 3.2.0-dev-5e57377 but the kernel is 4.1.1 - I guess that could be the issue.

**Comment by parente** [comment]
Yes. The extension is only compatible with notebook server 4.0 and up. The runtime directory location is different between the two versions.

**Comment by abjer** [comment]
I see, thanks for the clarification!
