### ISSUE TITLE
Unrecognized JSON config file version, assuming version 1

### ISSUE THREAD

**Issue by stubz01** [jupyter-incubator/contentmanagement#28]
The subject line is the error I received in the terminal window when trying to fire up jupyter notebook ...
Jupyter did open and I was able to open .ipynb's, it didn't recognize %load_ext jupyter_cms tho ...

I'm also wondering about this: 
# enable the JS and server extensions in your ~/.jupyter

jupyter cms activate
# deactivate it later with

jupyter cms deactivate

Why am I doing this ¿

Thoughts:

I am using condas, but had to install the jupyter_cms thru pip ...
The conda list showed jupyter_cms, but it wouldn't import into an environment I had created ...

Is there some conflict with condas and jupyter_cms ?
Have I not installed things in the right order ?
Maybe I've installed jupyter_cms in a different place then condas, than tried to lay it on top ?

This seems like an extremely useful extension, that will generate the type of results, I think I've been wanting to create, 
but haven't been able to wrap my head around the technicalities of linking this thing to that thing and using it for something else ...
I'd really like to be able to get this sorted as efficiently as you've made it look in your video ...

Cheerz

**Comment by parente** [comment]
It could be you're running into the problem that the new extension install/activate/deactive/uninstall support being added to Jupyter Notebook 4.2 is meant to address (see https://github.com/jupyter/notebook/pull/879). If you're working out of a conda environments, I bet you're going to have a bad time trying to get the extension to install and enable properly at the moment using the basic steps from the README.

That said, it might not be impossible. We'll need to kick the tires on what it takes to do in a custom conda env today. If you can include the bash history of what you ran, what conda env, you're in, etc. that would help a lot.

**Comment by stubz01** [comment]
I have been finding condas useful, but those notebooks in notebooks look usefuller ...
It's probably close to a reformat time any way ...
Is this what you were looking for ?
![snapshot1](https://cloud.githubusercontent.com/assets/7951963/14020383/85682b44-f19c-11e5-8512-399941a7f7f3.png)
![snapshot2](https://cloud.githubusercontent.com/assets/7951963/14020384/856849d0-f19c-11e5-9e16-e7e8ef5455eb.png)

**Comment by parente** [comment]
It looks like you're pip installing outside the conda environment. I see a source deactivate just before the pip install. Try:

```
source activate Proj01
pip install jupyter_cms
jupyter cms install --user --symlink --overwrite
jupyter cms activate
jupyter notebook
```

**Comment by stubz01** [comment]
I think I got it ...
Yesterday I think I installed the cms in condas and tried to import it into the Proj01 environment, not run the install command, inside the environment ...

**Comment by stubz01** [comment]
It still is coming up with the Unrecognized JSON config file and the./face.icon doesn't exist,
but I ran thru the cookbook example to apicook.help and saw the API Cookbook header and paragraph
:)

**Comment by parente** [comment]
Yea, the JSON config file thing is a warning about how the JSON is being loaded. It will go away when we can adopt the new extension installation mechanisms coming in Jupyter Notebook 4.2.

**Comment by parente** [comment]
I think this one is settled. Going to close. @stubz01 please reopen if I missed something in the chatter above.
