### ISSUE TITLE
Do a release on pypi

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/contentmanagement#4]
Most of these features probably belong in notebook proper. But since we've been focused on the other incubator projects at the moment, it probably makes sense to at least make these easily installable.

Do this once #3 lands. Probably automate it in the Makefile too.

**Comment by parente** [comment]
Released 0.1.0 mainly to test the flow ahead of dashboards / declarative widgets releasing. @jtyberg is going to test if everything went smoothly. Will keep this open til then.

**Comment by jtyberg** [comment]
A `pip install` fails for me.

```
$ pip install jupyter_cms
Downloading/unpacking jupyter-cms
  Could not find any downloads that satisfy the requirement jupyter-cms
Cleaning up...
No distributions at all found for jupyter-cms
```

Are we allowed to name the package (jupyter_cms) with an underscore?

**Comment by parente** [comment]
The 0.1.0 tarball never got associated with the jupyter_cms project on pypi for some reason. But when I try to upload it again, pypi says that file already exists.

I cut to the chase and did a 0.1.1 release. That pip installs fine for me.
