### ISSUE TITLE
Why ipython<5.0,>=4.1.0 (from jupyter-cms)?

### ISSUE THREAD

**Issue by rs2** [jupyter-incubator/contentmanagement#44]
`pip install jupyter-cms -U` uninstalls latest ipython. Why `<5.0,>=4.1.0`?

**Comment by parente** [comment]
It's over-pinned. We can take a PR to remove the 5.0 cap. It needs greater than 4.1 for a feature.

**Comment by ankostis** [comment]
This pinned dependency forcefully downgrades ipython, so it badly interacts with the rest of  incubator projects (dashboards, declarative widgets).
A new release would be greatly appreciated.
Thank you anyway.

**Comment by parente** [comment]
Released 0.6.0 with ipython unpinned.
