### ISSUE TITLE
jupyter cms quick-setup --sys-prefix not working

### ISSUE THREAD

**Issue by jmontoyam** [jupyter-incubator/contentmanagement#49]
Hi,
first of all, please excuse me if this is a silly question.

I have successfully installed the content manager package:
pip install jupyter_cms
Collecting jupyter_cms
Requirement already satisfied (use --upgrade to upgrade): whoosh<3.0,>=2.7.0 in ./anaconda/envs/mne_env_py2/lib/python2.7/site-packages (from jupyter_cms)
Requirement already satisfied (use --upgrade to upgrade): scandir<2.0,>=1.1 in ./anaconda/envs/mne_env_py2/lib/python2.7/site-packages (from jupyter_cms)
Requirement already satisfied (use --upgrade to upgrade): notebook<5.0,>=4.0.0 in ./anaconda/envs/mne_env_py2/lib/python2.7/site-packages (from jupyter_cms)
Requirement already satisfied (use --upgrade to upgrade): ipython>=4.1.0 in ./anaconda/envs/mne_env_py2/lib/python2.7/site-packages (from jupyter_cms)
Installing collected packages: jupyter-cms
Successfully installed jupyter-cms-0.6.1

But when I try to activate it I get the following error:

jupyter cms quick-setup --sys-prefix
Traceback (most recent call last):
  File "/home/user/anaconda/envs/mne_env_py2/bin/jupyter-cms", line 11, in <module>
    sys.exit(main())
  File "/home/user/anaconda/envs/mne_env_py2/lib/python2.7/site-packages/jupyter_cms/extensionapp.py", line 300, in main
    ExtensionApp.launch_instance()
  File "/home/user/anaconda/envs/mne_env_py2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/user/anaconda/envs/mne_env_py2/lib/python2.7/site-packages/jupyter_cms/extensionapp.py", line 297, in start
    super(ExtensionApp, self).start()
  File "/home/user/anaconda/envs/mne_env_py2/lib/python2.7/site-packages/traitlets/config/application.py", line 305, in start
    return self.subapp.start()
  File "/home/user/anaconda/envs/mne_env_py2/lib/python2.7/site-packages/jupyter_cms/extensionapp.py", line 202, in start
    from notebook import serverextensions
ImportError: cannot import name serverextensions

I'm running jupyter notebook 4.2.1

I would really appreciate any help you could give me.

P.S: I have installed and activated jupyter-dashboards, and it's working fine.

**Comment by parente** [comment]
Can you post the output of `conda list` with your `mne_env_py2` environment is active?

**Comment by jmontoyam** [comment]
Thank you very much for your quick answer.

Here it is the output of conda list when my mne_env_py2 is active:

# packages in environment at /home/user/anaconda/envs/mne_env_py2:

#
accelerate                1.10.0              np19py27_p0  
alabaster                 0.7.6                    py27_0  
appdirs                   1.4.0                     <pip>
apptools                  4.2.1                    py27_0  
babel                     2.1.1                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.4                      py27_0  
bokeh                     0.12.3                   py27_0  
cairo                     1.12.18                       6  
certifi                   14.05.14                 py27_0  
configobj                 5.0.6                    py27_0  
coverage                  3.7.1                    py27_0  
cudatoolkit               6.0                          p0  
cycler                    0.9.0                    py27_0  
dbus                      1.10.10                       0  
decorator                 4.0.9                    py27_0  
decorator                 3.4.2                     <pip>
docutils                  0.12                     py27_0  
enum34                    1.0.4                    py27_0  
envisage                  4.4.0                    py27_1  
expat                     2.1.0                         0  
flask                     0.10.1                   py27_1  
fontconfig                2.11.1                        6  
freetype                  2.5.5                         0  
funcsigs                  0.4                      py27_0  
futures                   3.0.3                    py27_0  
get_terminal_size         1.0.0                    py27_0  
glib                      2.43.0                        1  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
h5py                      2.4.0                np19py27_0  
hdf5                      1.8.14                        0  
icu                       54.1                          0  
ipykernel                 4.1.1                    py27_0  
ipython                   5.1.0                    py27_0  
ipython-notebook          4.0.4                    py27_0  
ipython-qtconsole         4.0.1                    py27_0  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                4.1.0                    py27_0  
itsdangerous              0.24                     py27_0  
jedi                      0.9.0                    py27_0  
jinja2                    2.8                      py27_0  
joblib                    0.9.4                    py27_0  
jpeg                      8d                            0  
jsonschema                2.4.0                    py27_0  
jupyter                   1.0.0                    py27_3  
jupyter-cms               0.6.1                     <pip>
jupyter-dashboards        0.6.1                     <pip>
jupyter_client            4.4.0                    py27_0  
jupyter_console           5.0.0                    py27_0  
jupyter_core              4.2.0                    py27_0  
lcms                      1.19                          0  
libffi                    3.2.1                         0  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libpng                    1.6.22                        0  
libsodium                 1.0.3                         0  
libtiff                   4.0.2                         1  
libxcb                    1.12                          0  
libxml2                   2.9.2                         0  
line-profiler             1.0                       <pip>
llvmlite                  0.5.0                    py27_0  
markupsafe                0.23                     py27_0  
matplotlib                1.5.3               np111py27_0  
mayavi                    4.4.0                np19py27_0  
mistune                   0.7.1                    py27_0  
mkl                       11.3.3                        0  
mkl-rt                    11.1                         p0  
mkl-service               1.0.0                   py27_p1  
mklfft                    2.0                 np19py27_p0  
nbconvert                 4.0.0                    py27_0  
nbformat                  4.0.1                    py27_0  
nibabel                   2.0.0                     <pip>
nitime                    0.5                       <pip>
nose                      1.3.7                    py27_0  
notebook                  4.0.6                    py27_0  
numba                     0.19.1               np19py27_0  
numbapro                  0.17.1              np19py27_p0  
numbapro_cudalib          0.2                           0  
numexpr                   2.6.0               np111py27_0  
numpy                     1.11.2                   py27_0  
openssl                   1.0.2g                        0  
pandas                    0.19.0              np111py27_0  
path.py                   8.1.2                    py27_1  
pathlib2                  2.1.0                    py27_0  
patsy                     0.4.1                    py27_0  
pep8                      1.6.2                    py27_0  
pexpect                   3.3                      py27_0  
pickleshare               0.5                      py27_0  
pil                       1.1.7                    py27_1  
pillow                    2.8.1                    py27_1  
pip                       8.1.2                    py27_0  
pixman                    0.32.6                        0  
prompt_toolkit            1.0.3                    py27_0  
psutil                    3.2.2                    py27_0  
ptyprocess                0.5                      py27_0  
pudb                      2015.4.1                  <pip>
py                        1.4.26                    <pip>
py2cairo                  1.10.0                   py27_2  
pycairo                   1.10.0                   py27_0  
pycuda                    2014.1                    <pip>
pydicom                   0.9.9                     <pip>
pyface                    4.4.0                    py27_0  
pyflakes                  1.0.0                    py27_0  
pygments                  2.0.2                    py27_0  
pygraphviz                1.2                       <pip>
pyparsing                 2.0.3                    py27_0  
pyqt                      5.6.0                    py27_0  
pysurfer                  0.5                       <pip>
pytest                    2.7.0                     <pip>
python                    2.7.11                        0  
python-dateutil           2.5.0                    py27_0  
pytools                   2014.3.5                  <pip>
pytz                      2016.1                   py27_0  
pyyaml                    3.11                     py27_1  
pyzmq                     14.7.0                   py27_1  
qt                        5.6.0                         1  
qtconsole                 4.2.1                    py27_1  
readline                  6.2                           2  
requests                  2.9.1                    py27_0  
rope                      0.9.4                    py27_1  
scandir                   1.3                      py27_0    conda-forge
scandir                   1.3                       <pip>
scikit-learn              0.17.1              np111py27_1  
scikits.cuda              0.42                      <pip>
scipy                     0.18.1              np111py27_0  
setuptools                20.3                     py27_0  
simplegeneric             0.8.1                    py27_0  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.0                    py27_0  
sphinx                    1.3.1                    py27_0  
sphinx_rtd_theme          0.1.7                    py27_0  
spyder                    2.3.7                    py27_1  
sqlite                    3.9.2                         0  
ssl_match_hostname        3.4.0.2                  py27_0  
statsmodels               0.6.1               np111py27_1  
system                    5.8                           2  
terminado                 0.5                      py27_1  
tk                        8.5.18                        0  
tornado                   4.3                      py27_0  
traitlets                 4.3.1                    py27_0  
traits                    4.5.0                    py27_0  
traitsui                  4.4.0                    py27_0  
urwid                     1.3.1                     <pip>
vtk                       5.10.1                   py27_1  
wcwidth                   0.1.7                    py27_0  
werkzeug                  0.10.4                   py27_0  
wheel                     0.29.0                   py27_0  
Whoosh                    2.7.4                     <pip>
whoosh                    2.7.4                    py27_0  
winpdb                    1.3.6                     <pip>
yaml                      0.1.6                         0  
zeromq                    4.1.3                         0  
zlib                      1.2.8                         0

**Comment by parente** [comment]
The list shows that notebook 4.0.6 is installed in that environment not 4.2. You can upgrade your notebook or use the legacy install steps for cms.

**Comment by jmontoyam** [comment]
Thank you very much!, I run conda update notebook as you suggested me and now everything works!.
Please excuse me my beginner question!, when I run jupyter notebook --version it returns  4.2.1, therefore I supposed that my notebook version was 4.2.1, I didn't know that notebook and jupyter were 2 different packages, please excuse me my beginner confusion!.

Once again, thank you very much for all your help, and for your patience! :-).

**Comment by parente** [comment]
You're welcome.
