### ISSUE TITLE
loadnotebook() not working with nbconvert 5.0.0

### ISSUE THREAD

**Issue by linuxrider** [jupyter-incubator/contentmanagement#50]
The loadnotebook() (from loader.py) relies on export_html from nbconvert which is not present with nbconvert 5.0.0.
It seams to have been moved to nbconvert.exporters.html.
Possible solution:
In loader.py change 
**from nbconvert import export_html**
to
**from nbconvert.exporters import html as export_html**

**Comment by parente** [comment]
Thanks for the report. I see the problem here (and maybe another). I'll get a PR in soon.
